// lib/board-brief.ts — CEO Stability Brief generator (PDF 2 Part IV §17)
// Based on the 3 non-negotiable questions every CEO must answer.

export interface BriefInput {
  orgName: string;
  oss: number;
  ri: number;
  er: number;
  pr: number;
  a: number;
  hpLrTrap: boolean;
  maxReachableOSS: number;
  riskZoneName: string;
  trendAlert: 'none' | 'yellow' | 'red';
}

export interface BriefOutput {
  markdown: string;
  q1: string; // overload point
  q2: string; // recovery window compression
  q3: string; // synchronization mismatch
}

export function generateBrief(input: BriefInput): BriefOutput {
  const { orgName, oss, ri, er, pr, a, hpLrTrap, maxReachableOSS, riskZoneName, trendAlert } = input;

  // Q1: Where is the current organizational overload point?
  const overloadPoint = hpLrTrap
    ? `**Critical overload detected.** Your organization is in the HP/LR Trap — execution (ER=${er}) and pressure regulation (PR=${pr}) are high, but recovery integrity (RI=${ri}) is critically low. The overload point is NOW. Every additional initiative pushes the system closer to structural failure.`
    : ri < 55
      ? `The overload point is approaching. Recovery Integrity (RI=${ri}) is below the critical threshold of 55. The organization is absorbing more pressure than it can recover from. Additional acceleration without recovery investment will trigger destabilization.`
      : ri < 70
        ? `The overload point is emerging. RI=${ri} indicates moderate recovery strain. While not critical, the trend suggests the organization is stretching toward its structural capacity. Monitor quarterly.`
        : `No immediate overload detected. RI=${ri} is healthy. The organization has structural capacity for measured acceleration, but should maintain recovery protocols.`;

  // Q2: Is the recovery window being compressed?
  const recoveryWindow = a > 70
    ? `**Yes — severely compressed.** Acceleration Intensity (A=${a}) is in the high-risk zone. At this acceleration level, the maximum achievable OSS is ${maxReachableOSS} (not 100). Recovery windows are being squeezed by continuous initiative expansion. The board must protect recovery time as a structural asset.`
    : a > 50
      ? `Partially compressed. A=${a} is moderate. Recovery windows exist but are shrinking. If acceleration increases without proportional recovery investment, the window will close.`
      : `Not significantly compressed. A=${a} is manageable. Recovery windows are intact. The organization can sustain current acceleration without structural risk.`;

  // Q3: Is there a synchronization mismatch?
  const syncMismatch = hpLrTrap
    ? `**Yes — severe mismatch.** The Performance Rhythm (high ER/PR) and Stabilization Rhythm (low RI) have fallen out of phase. This is the defining condition of the HP/LR Trap. The organization is executing forcefully but not recovering. This mismatch produces oscillation and, eventually, nonlinear collapse.`
    : ri < er * 0.7
      ? `Emerging mismatch. Recovery Integrity (RI=${ri}) is significantly below Execution Rhythm (ER=${er}). The performance rhythm is outpacing the stabilization rhythm. Action: rebalance by investing in recovery before further acceleration.`
      : `No significant mismatch. Performance and stabilization rhythms are approximately in phase (RI=${ri}, ER=${er}). Maintain current rhythm discipline.`;

  const markdown = `# CEO Stability Brief — ${orgName}

## The OSS Index™: ${oss} (${riskZoneName})

${trendAlert !== 'none' ? `**${trendAlert === 'red' ? '🔴 RED ALERT' : '🟡 YELLOW ALERT'}** — OSS™ has changed significantly since last assessment.\n\n` : ''}---

## The Three Non-Negotiable Questions

### 1. Where is the current organizational overload point?

${overloadPoint}

### 2. Is the recovery window being compressed?

${recoveryWindow}

### 3. Is there a synchronization mismatch?

${syncMismatch}

---

## Key Metrics

| Metric | Value | Status |
|--------|-------|--------|
| OSS™ Score | ${oss} | ${riskZoneName} |
| Execution Rhythm (ER) | ${er} | ${er >= 70 ? 'Strong' : er >= 50 ? 'Moderate' : 'Weak'} |
| Pressure Regulation (PR) | ${pr} | ${pr >= 70 ? 'Strong' : pr >= 50 ? 'Moderate' : 'Weak'} |
| Recovery Integrity (RI) | ${ri} | ${ri >= 70 ? 'Healthy' : ri >= 55 ? 'At Risk' : 'Critical'} |
| Acceleration (A) | ${a} | ${a > 70 ? 'High Risk' : a > 50 ? 'Moderate' : 'Manageable'} |
| Max Reachable OSS | ${maxReachableOSS} | Given A=${a} |
| HP/LR Trap | ${hpLrTrap ? '🚨 DETECTED' : 'Not triggered'} | — |

---

*Generated by Dual-Rhythm Architecture™ · Powered by The OSS Index™ · DOI: 10.5281/zenodo.19941449*
`;

  return { markdown, q1: overloadPoint, q2: recoveryWindow, q3: syncMismatch };
}
